## I created this playbook to check all docker processes running in a list of IP's with a single username/password combination

---
- name: Check container names
  hosts: container_names
  remote_user: mahesh.rijal
  become: yes
  gather_facts: no

  tasks:
  
    - name: Check all running containers
      become: yes
      command: docker ps --format "{{ '{{' }} .Names {{ '}}' }}"
      register: dkr_ps
      
    - name: Pring all running container names    
      debug: msg="{{dkr_ps.stdout_lines}}"

    #- local_action: copy content={{ dkr_ps.stdout_lines }} dest=/home/sdp/ansible/playbookoutput.txt

    - name: Copy results to a file
      lineinfile:
        line: "{{ dkr_ps }}"
        insertafter: EOF
        dest: /home/mhs/ansible/playbookoutput.txt
      delegate_to: 127.0.0.1
